import {VERSION,DEFAULT_SETTINGS} from "./config.js?v=2.4.6";
import {TYPES,finite,id,taipeiDay,stamp,num,money,compact,signed,esc,normalizeAsset,valuation,portfolio,requiredRates,sharedAsset,parseAsset} from "./core.js";
import {refreshMarket} from "./quotes.js";
import {icon} from "./icons.js";
import {buildBackup,parseBackup} from "./backup.js";
import * as cloud from "./store.js";

const $=name=>document.getElementById(name);
const PAGES={home:["總覽","OVERVIEW"],assets:["我的持倉","PORTFOLIO"],sharing:["共享空間","SHARED SPACE"],history:["資產紀錄","HISTORY"],settings:["設定","PREFERENCES"]};
const colors=["#e3b34c","#b29f70","#798d80","#a5a68b","#647b70","#c7b786"];
const s={user:null,demo:false,page:"home",assets:[],history:[],settings:{...DEFAULT_SETTINGS},published:{assets:[],viewerUids:[]},strategyAccess:{viewerUids:[]},friends:[],ownPosts:[],friendPosts:[],invites:{sent:[],received:[]},sharingTab:"portfolios",friend:"self",search:"",filter:"all",sort:"value",historyArchivePage:0,historyArchiveOpen:false,refreshing:false,lastRefresh:0,selected:[],portfolioViewers:[],strategyViewers:[],shareDirty:false,settingsDirty:false,dirtyForms:new Set(),inviteEmail:"",subscriptions:[],session:0};
let firebaseReady=false,toastTimer,editingAsset=null,editingPost=null,pendingConfirmation=null,authUnsubscribe=null,adminRequest=null;

function toast(message,error=false){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").className="toast visible"+(error?" error":"");toastTimer=setTimeout(()=>$("toast").classList.remove("visible"),error?6500:3500);}
function message(error){if(error?.code==="permission-denied")return "權限不足。若這是第一次更新新版，請先依更新說明發布新版 Firestore 規則。";return error?.message||"操作失敗，請稍後再試。";}
async function task(button,fn,errorElement=null){const old=button?.innerHTML;if(button){button.disabled=true;button.innerHTML="處理中…";}document.body.classList.add("saving");try{if(errorElement)errorElement.textContent="";await fn();}catch(e){if(errorElement)errorElement.textContent=message(e);toast(message(e),true);}finally{document.body.classList.remove("saving");if(button){button.disabled=false;if(button.innerHTML==="處理中…")button.innerHTML=old;}}}
function pnl(value,percent=null){if(!finite(value))return '<span class="muted">未設定成本／待更新</span>';return `<span class="${value>=0?"up":"down"}">${signed(value)}${finite(percent)?` <small>(${value>0?"+":""}${num(percent,2)}%)</small>`:""}</span>`;}
function badge(text,kind=""){return `<span class="badge ${kind}">${esc(text)}</span>`;}
function quoteText(a){if(a.mode==="manual")return "手動輸入";if(a.quote?.error)return a.quote.error;if(a.mode==="tw"&&!a.quote?.priceAt)return "收盤價 · 查詢 "+stamp(a.quote?.fetchedAt);return "行情 "+stamp(a.quote?.priceAt||a.quote?.fetchedAt);}
function assetAccent(symbol){const palette=["#e3b34c","#65a98b","#7b9ad1","#bd82ba","#d88764","#7eb8bd"];const sum=[...String(symbol||"asset").toUpperCase()].reduce((n,c)=>n+c.charCodeAt(0),0);return palette[sum%palette.length];}
function assetIcon(a){const symbol=(a.symbol||a.name||"USD").trim();const label=a.mode==="manual"?"$":symbol.slice(0,1).toUpperCase();return `<span class="asset-icon ${esc(a.mode)}" style="--asset-accent:${assetAccent(symbol)}" aria-label="${esc(symbol)} 標的圖示">${esc(label)}</span>`;}
function googlePhotoUrl(value){try{const url=new URL(value);return url.protocol==="https:"&&(url.hostname==="googleusercontent.com"||url.hostname.endsWith(".googleusercontent.com"))?url.href:"";}catch{return "";}}
function avatarContent(user=s.user){const photo=googlePhotoUrl(user?.photoURL);return photo?`<img class="avatar-photo" src="${esc(photo)}" alt="" referrerpolicy="no-referrer">`:esc(user?.displayName?.slice(0,1)||"W");}
function heading(description,actions=""){const [title,kicker]=PAGES[s.page];return `<div class="page-heading"><div class="heading-title"><div class="eyebrow">${kicker}</div><h1>${title}</h1></div>${actions?`<div class="heading-actions">${actions}</div>`:""}<p class="page-description">${description}</p></div>`;}
function empty(title,text,action="",name="assets"){return `<div class="empty-state"><div class="empty-icon">${icon(name)}</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;}
function refreshButton(action="refresh"){return `<button class="button secondary refresh-button" aria-label="${s.refreshing?'更新報價中':'更新報價'}" title="更新報價" data-action="${action}" ${s.refreshing?"disabled":""}>${icon("refresh")}<span>${s.refreshing?"更新中":"更新報價"}</span></button>`;}
function graph(history,height=152){const entries=history.slice(-30);if(entries.length<2)return '<div class="chart-empty">累積兩筆紀錄後，顯示資產曲線。</div>';const min=Math.min(...entries.map(x=>x.total)),max=Math.max(...entries.map(x=>x.total)),span=(max-min)||Math.max(max*.01,1);const pts=entries.map((x,i)=>[12+i*576/(entries.length-1),height-20-(x.total-min)/span*(height-45)]);const path=pts.map((p,i)=>(i?"L":"M")+p.map(v=>v.toFixed(2)).join(" ")).join(" ");const last=pts.at(-1);return `<svg class="chart" viewBox="0 0 600 ${height}" preserveAspectRatio="none" role="img" aria-label="最近 ${entries.length} 筆資產變化"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#e3b34c" stop-opacity=".14"/><stop offset="1" stop-color="#e3b34c" stop-opacity="0"/></linearGradient></defs>${[35,80,125].map(y=>`<path d="M0 ${y}H600" stroke="#2a362f" stroke-dasharray="3 6"/>`).join("")}<path d="${path} L${last[0]} ${height} L12 ${height}Z" fill="url(#chartFill)"/><path d="${path}" stroke="#e3b34c" stroke-width="2.3" fill="none" vector-effect="non-scaling-stroke"/><circle cx="${last[0]}" cy="${last[1]}" r="4" fill="#e3b34c" stroke="#18211c" stroke-width="3"/></svg><div class="chart-labels"><span>${esc(entries[0].date.slice(5))}</span><span>${esc(entries[Math.floor(entries.length/2)].date.slice(5))}</span><span>${esc(entries.at(-1).date.slice(5))}</span></div>`;}
function allocation(){const map=new Map();for(const a of s.assets){const v=valuation(a);if(a.isSummary||!finite(v.value)||v.value<=0)continue;const label=a.mode==="manual"?(a.type||"其他"):TYPES[a.mode];map.set(label,(map.get(label)||0)+v.value);}const entries=[...map.entries()].sort((a,b)=>b[1]-a[1]);const total=entries.reduce((sum,x)=>sum+x[1],0);if(!total)return empty("配置尚未建立","新增資產後即可查看分布。","","assets");let cursor=0;const parts=entries.map(([_,value],i)=>{const start=cursor;cursor+=value/total*100;return `${colors[i%colors.length]} ${start}% ${cursor}%`;});return `<div class="allocation"><div class="donut" style="background:conic-gradient(${parts.join(",")})"><div class="donut-label">${entries.length}<small>資產類別</small></div></div><div class="legend">${entries.map(([label,value],i)=>`<div class="legend-row"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span><span>${esc(label)}</span><span class="percent mono">${num(value/total*100,1)}%</span></div>`).join("")}</div></div>`;}
function home(){
  const p=portfolio(s.assets),goal=+s.settings.goal||1;
  const progress=Math.min(100,p.total/goal*100),rates=requiredRates(s.assets,s.settings);
  const latest=s.assets.map(a=>a.quote?.fetchedAt).filter(Boolean).sort().at(-1);
  const priceOnly=s.assets.some(a=>!a.isSummary&&valuation(a).kind.includes("未計匯差"));
  const amountClass=String(Math.round(p.total)).length>9?" long-amount":"";
  return `${heading("持倉與目標，一眼掌握。")}
    <div class="overview-grid"><section class="hero wealth-summary" aria-label="資產總覽">
      <div class="summary-heading"><span>目前總資產</span><span class="summary-currency">NT$ · 台幣</span></div>
      <div class="summary-amount mono${amountClass}">${num(p.total,0)}</div>
      <p class="summary-holdings">${p.count} 個持倉${p.stale?`<span class="gold"> · ${p.stale} 筆行情待確認</span>`:""}</p>
      <div class="summary-return">
        <div class="summary-return-label">目前浮動損益</div>
        <div class="summary-pnl mono">${pnl(p.pnl,p.percent)}</div>
        <details class="summary-method"><summary>損益計算說明 ${icon("chevron")}</summary><p>${p.covered} / ${p.count} 筆已設定成本。未填成本的部位不計入損益。${priceOnly?"部分美元部位未填買入匯率，損益未計入匯差。":""}</p></details>
      </div>
      <div class="summary-footer"><div class="summary-updated"><span>行情更新</span><span class="mono">${latest?stamp(latest):"尚未取得行情"}</span></div><button class="button secondary summary-refresh" data-action="refresh" ${s.refreshing?"disabled":""}>${icon("refresh")}${s.refreshing?"更新中…":"更新報價"}</button></div>
    </section>
    <div class="home-grid">
      <section class="card trend-card"><div class="card-header"><h2>資產變化</h2><button class="text-button" data-page="history">查看紀錄 ${icon("arrow")}</button></div>${graph(s.history,165)}</section>
      <section class="card goal-card"><div class="card-header"><h2>目標進度</h2><button class="text-button" data-page="settings">調整</button></div><div class="goal-top"><span class="goal-percent mono">${num(progress,1)}<small>%</small></span><span class="small muted">${esc(s.settings.targetDate)}</span></div><div class="progress"><span style="width:${Math.max(0,progress)}%"></span></div><div class="goal-detail"><div>距離目標<strong class="mono">${compact(Math.max(0,goal-p.total))}</strong></div><div>目標金額<strong class="mono">${compact(goal)}</strong></div></div><div class="goal-foot"><span class="muted">${rates.state==="done"?"目標已達成":rates.state==="expired"?"目標日期已到期":`剩餘約 ${Math.ceil(rates.days||0)} 天`}</span><span class="muted">每月投入 ${compact(+s.settings.monthly||0)}</span></div></section>
    </div>
    </div><details class="card disclosure"><summary>資產配置與達標試算</summary><div class="disclosure-body"><div class="analysis-grid"><section><h2>資產配置</h2>${allocation()}<p class="rate-note" style="margin-top:18px">已設定成本本金 ${money(p.cost)}。未填成本的部位不計入損益本金。</p></section><section><h2>達標所需報酬</h2>${ratesHtml(rates)}</section></div></div></details>`;
}
function ratesHtml(r){const texts={noCapital:"請先新增資產或設定每月投入，才能計算所需報酬。",expired:"目標日期已到期，請到設定調整。",done:"你已達成目標，可以設定下一個里程碑。",invalid:"請先確認目標金額、日期與投入金額。",unsolved:"目前條件無法得到有效結果，請調整目標或日期。",contributions:"依此試算，每月投入已足以達標，不需額外投資報酬。"};if(r.state!=="calculated")return `<p class="rate-note">${texts[r.state]||"請先設定目標。"}</p>`;return `<div class="rates-grid"><div class="rate-box"><div class="label">年報酬</div><div class="value gold mono">${num(r.ry*100,1)}%</div></div><div class="rate-box"><div class="label">月報酬</div><div class="value mono">${num(r.rm*100,2)}%</div></div><div class="rate-box"><div class="label">日報酬</div><div class="value mono">${num(r.rd*100,3)}%</div></div></div><p class="rate-note">以固定複利、每月投入近似試算。這是達標條件，不代表可實現的投資報酬。${r.ry>1?"<br><span class=\"gold\">所需年報酬偏高，可調整期限、目標或投入。</span>":""}</p>`;}

function assetRows(assets,editable=true){if(!assets.length)return empty("目前沒有持倉","新增資產，或調整搜尋條件。",editable?'<button class="button secondary" data-action="add-asset">新增持倉</button>':"");return `<div class="table-wrap"><table class="asset-table ${editable?'':'readonly'}"><thead><tr><th>持倉 / 類別</th><th class="qty-col">數量 / 均價</th><th class="price-col">原幣報價</th><th>市值 / 損益</th>${editable?"<th></th>":""}</tr></thead><tbody>${assets.map(a=>{const v=valuation(a),native=a.mode==="manual"?"—":a.mode==="usd"?"美元資產":`${num(v.price,a.mode==="crypto"?6:2)} ${v.currency}`;const meta=a.mode==="manual"?"手動輸入":`${num(+a.qty||0,6)} ${a.mode==="stock"||a.mode==="tw"?"股":a.mode==="usd"?"USD":"顆"}`;return `<tr><td><div class="asset-name">${assetIcon(a)}<div><div class="asset-title">${esc(a.name)}</div><div class="asset-sub">${a.symbol?esc(a.symbol)+" · ":""}${esc(a.mode==="manual"?a.type:TYPES[a.mode])} · ${esc(meta)}${a.isSummary?" · 參考值":""}</div><div class="asset-quote ${v.stale?"gold":""}">${esc(quoteText(a))}</div></div></div></td><td class="qty-col mono">${num(+a.qty||0,6)}<div class="asset-sub">${a.costPer?num(+a.costPer,4)+" "+v.currency:"成本未填"}</div></td><td class="price-col mono">${native}<div class="asset-sub">${a.quote?.source?esc(a.quote.source):""}</div></td><td class="value-cell"><div class="money mono">${money(v.value)}</div><div class="pnl-percent mono">${pnl(v.pnl,v.percent)}</div>${finite(v.nativeValue)&&v.currency==="USD"?`<div class="asset-sub mono">${v.stale?"上次成功市值":"美元市值估算"} · 約 US$ ${num(v.nativeValue,0)}</div>`:""}</td>${editable?`<td class="action-cell"><div class="table-actions"><button class="icon-button" data-action="edit-asset" data-id="${esc(a.id)}" aria-label="編輯 ${esc(a.name)}">${icon("edit")}</button><button class="icon-button" data-action="delete-asset" data-id="${esc(a.id)}" aria-label="刪除 ${esc(a.name)}">×</button></div></td>`:""}</tr>`;}).join("")}</tbody></table></div>`;}
function filteredAssets(){const q=s.search.toLowerCase();return s.assets.filter(a=>(s.filter==="all"||a.mode===s.filter)&&(!q||(a.name+" "+a.symbol).toLowerCase().includes(q))).sort((a,b)=>s.sort==="name"?a.name.localeCompare(b.name):s.sort==="pnl"?(valuation(b).pnl??-Infinity)-(valuation(a).pnl??-Infinity):(valuation(b).value||0)-(valuation(a).value||0));}
function assetsPage(){const p=portfolio(s.assets);return `${heading(`${p.count} 個持倉 · 總資產 ${money(p.total)}`)}<section class="card"><div class="holdings-actions"><h2>持倉列表</h2><div class="card-actions">${refreshButton()}<button class="button secondary card-action" data-action="add-asset">${icon("plus")}新增持倉</button></div></div><div class="toolbar"><div class="search-field">${icon("search")}<input id="assetSearch" placeholder="搜尋名稱或代號" value="${esc(s.search)}" aria-label="搜尋持倉"></div><select id="assetFilter" aria-label="資產類別"><option value="all">所有類別</option>${Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${s.filter===k?"selected":""}>${v}</option>`).join("")}</select><select id="assetSort" aria-label="排序"><option value="value" ${s.sort==="value"?"selected":""}>市值高 → 低</option><option value="pnl" ${s.sort==="pnl"?"selected":""}>損益高 → 低</option><option value="name" ${s.sort==="name"?"selected":""}>名稱排序</option></select></div><div id="assetRows">${assetRows(filteredAssets())}</div><p class="table-note">美元部位未填買入匯率時，只顯示按目前匯率換算的價差損益；行情與匯率可能有延遲。帳戶總值設為參考值時，不會重複計入總資產。</p></section>`;}

function sharing(){const own=s.friend==="self",friend=s.friends.find(x=>x.id===s.friend),selected=s.sharingTab;const choices=`<select id="friendSelect" class="friend-select" aria-label="查看對象"><option value="self">我的分享與草稿</option>${s.friends.map(f=>`<option value="${esc(f.id)}" ${s.friend===f.id?"selected":""}>${esc(f.ownerName||"朋友")}</option>`).join("")}</select>`;const action=own&&selected!=="portfolios"?`<button class="button primary" data-action="add-strategy">${icon("plus")}新增策略</button>`:!own&&selected==="portfolios"&&friend?.portfolioAccess?refreshButton("refresh-friend"):!own&&selected!=="portfolios"?`<button class="button secondary" data-action="reload-sharing">${icon("refresh")}重新整理</button>`:"";return `${heading("把選擇分享的部位，與背後的交易想法放在一起。",action)}<div class="sharing-top"><div class="segment" role="group" aria-label="共享分類">${[["portfolios","持倉共享"],["long","長線策略"],["short","短線策略"]].map(([key,text])=>`<button data-tab="${key}" class="${selected===key?"active":""}">${text}</button>`).join("")}</div>${choices}</div>${selected==="portfolios"?(own?publishPage():friend?.portfolioAccess?friendPortfolio(friend):empty("尚未取得持倉授權","對方目前只分享策略，或尚未開啟持倉共享。","","lock")):strategyPage(own,friend,selected)}${own?invitesHtml():""}`;}
function publishPage(){const accepted=s.invites.sent.filter(i=>i.status==="accepted");const last=s.published.updatedAt;return `<div class="share-note">${icon("lock")}<span>預設私人。你選取的持倉，才會分享給勾選的朋友；朋友只能查看。持倉與策略的授權分開設定。</span></div><div class="share-grid"><section class="card"><div class="card-header"><div><div class="eyebrow">CHOOSE WHAT TO SHARE</div><h2>分享哪些持倉</h2></div>${badge(s.selected.length+" 筆","gold")}</div>${s.assets.length?s.assets.map(a=>`<label class="checkbox-row share-asset-choice"><input type="checkbox" data-share-asset="${esc(a.id)}" ${s.selected.includes(a.id)?"checked":""}><span>${esc(a.name)}<small class="muted"> · ${esc(TYPES[a.mode])}</small></span><span class="amount mono">${money(valuation(a).value)}</span></label>`).join(""):empty("先新增持倉","你可以只分享部分資產。",'<button class="button secondary" data-action="add-asset">新增持倉</button>')}</section><section class="card"><div class="card-header"><div><div class="eyebrow">YOUR TRUSTED CIRCLE</div><h2>分享給誰</h2></div>${icon("users")}</div>${accepted.length?accepted.map(i=>`<div class="contact"><div class="contact-top"><span class="contact-name">${esc(i.recipientEmail)}</span><button class="text-button" data-action="revoke" data-id="${esc(i.viewerUid)}">撤銷</button></div><div class="contact-choices"><label class="checkbox-row"><input type="checkbox" data-portfolio-viewer="${esc(i.viewerUid)}" ${s.portfolioViewers.includes(i.viewerUid)?"checked":""}><span>持倉</span></label><label class="checkbox-row"><input type="checkbox" data-strategy-viewer="${esc(i.viewerUid)}" ${s.strategyViewers.includes(i.viewerUid)?"checked":""}><span>策略</span></label></div></div>`).join(""):empty("邀請一位朋友","在下方輸入對方的 Google 帳號；接受後可選擇授權。","","users")}</section></div><div class="publish-row"><span class="small muted">${s.shareDirty?"有尚未儲存的分享設定":last?"最後分享更新 "+stamp(last):"尚未發布任何持倉"}</span><button class="button primary" data-action="publish">${icon("check")}儲存分享設定</button></div>`;}
function friendPortfolio(f){const p=portfolio(f.assets||[]);return `<section class="hero"><div class="hero-top"><span class="eyebrow">${esc(f.ownerName)} · 已分享的持倉</span>${badge("唯讀","green")}</div><div class="hero-amount mono${String(Math.round(p.total)).length>9?' long-amount':''}"><span class="currency">NT$</span><span class="amount-value">${num(p.total,0)}</span></div><div class="hero-bottom"><div><div class="hero-pnl mono">${pnl(p.pnl,p.percent)}</div><div class="hero-pnl-caption">${p.covered} 筆已設定成本 · 僅包含對方分享的持倉</div></div><div class="quote-state">持倉同步 ${stamp(f.updatedAt)}<br>${f.localRefreshed?"你的行情查詢 "+stamp(f.localRefreshed):"行情依各部位時間"}</div></div></section><section class="card" style="margin-top:18px">${assetRows(f.assets||[],false)}<p class="table-note">${f.localRefreshed?"目前使用你查詢的行情估值，未修改對方持倉。":"可用自己的報價來源更新估值；對方的持倉數量仍以最後分享內容為準。"}</p></section>`;}
function strategyPage(own,friend,term){if(!own&&!friend?.strategyAccess)return empty("尚未取得策略授權","請對方在分享設定勾選策略授權。","","lock");const posts=(own?s.ownPosts:s.friendPosts).filter(p=>p.term===term&&(own||p.published===true)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return posts.length?`<div class="strategy-grid">${posts.map(p=>`<article class="strategy-card"><div class="strategy-top"><span class="strategy-symbol">${esc(p.symbol)}</span>${badge({watching:"觀察中",active:"執行中",closed:"已結束"}[p.status]||"觀察中",p.status==="active"?"green":"")}</div><h2>${esc(p.title)}</h2><p class="thesis">${esc(p.thesis)}</p><dl class="strategy-info">${[["進場條件",p.entry],["失效／退出條件",p.invalidation],["目標／持有時間",p.target]].filter(x=>x[1]).map(([title,text])=>`<div><dt>${title}</dt><dd>${esc(text)}</dd></div>`).join("")}</dl><div class="strategy-bottom"><span>${own?(p.published?"已分享":"私人草稿")+" · ":""}建立 ${stamp(p.createdAt)}<br>修改 ${stamp(p.updatedAt)}</span>${own?`<div><button class="text-button" data-action="edit-strategy" data-id="${esc(p.id)}">編輯</button><button class="text-button down" data-action="delete-strategy" data-id="${esc(p.id)}" style="margin-left:10px">刪除</button></div>`:badge("唯讀")}</div></article>`).join("")}</div>`:empty(own?"記下你的第一個策略":"目前沒有已分享的策略",own?"把交易理由與失效條件一起記錄，之後更容易回顧。":"對方尚未分享這個週期的交易策略。",own?'<button class="button secondary" data-action="add-strategy">新增策略</button>':"","document");}
function invitesHtml(){const received=s.invites.received.filter(i=>i.status==="pending");return `<section class="card" style="margin-top:22px"><div class="card-header"><div><div class="eyebrow">INVITE & CONNECT</div><h2>邀請與連結</h2></div><button class="text-button" data-action="reload-sharing">重新整理</button></div><p class="small muted">對方需先登入並取得 App 使用授權。接受邀請後，你再選擇分享給對方的內容。</p><form id="inviteForm" class="invite-form"><input type="email" name="email" placeholder="朋友的 Google 帳號" value="${esc(s.inviteEmail)}" aria-label="朋友 Google 帳號" required><button class="button secondary" type="submit">送出邀請</button></form><div class="invite-list">${received.map(i=>`<div class="invite-item"><div>${esc(i.ownerName)} 邀請你查看分享</div><button class="text-button" data-action="accept-invite" data-id="${esc(i.id)}">接受邀請</button></div>`).join("")}${s.invites.sent.filter(i=>i.status==="pending").map(i=>`<div class="invite-item"><div>${esc(i.recipientEmail)}<div class="muted small">等待對方接受</div></div><button class="text-button" data-action="cancel-invite" data-id="${esc(i.id)}">取消</button></div>`).join("")}</div></section>`;}

function historyTable(entries,ordered){return `<div class="table-wrap"><table class="history-table"><thead><tr><th>日期</th><th>總資產</th><th>較前筆</th></tr></thead><tbody>${entries.map(h=>{const index=ordered.findIndex(x=>x.date===h.date),previous=ordered[index-1];return `<tr><td class="mono">${esc(h.date)}</td><td class="mono">${money(h.total)}</td><td class="mono">${previous?pnl(h.total-previous.total):"—"}</td></tr>`;}).join("")}</tbody></table></div>`;}
function historyPage(){
  const p=portfolio(s.assets),ordered=[...s.history].sort((a,b)=>a.date.localeCompare(b.date));
  const recent=ordered.slice(-10).reverse(),older=ordered.slice(0,-10).reverse();
  const pageCount=Math.ceil(older.length/10),page=Math.min(Math.max(0,s.historyArchivePage),Math.max(0,pageCount-1));
  s.historyArchivePage=page;
  const olderPage=older.slice(page*10,page*10+10);
  const archive=older.length?`<details id="olderHistory" class="history-archive" ${s.historyArchiveOpen?"open":""}><summary><span>較早紀錄 <small>${older.length} 筆</small></span><span class="archive-expand">展開</span><span class="archive-collapse">收起</span></summary><div class="archive-content">${historyTable(olderPage,ordered)}${pageCount>1?`<div class="archive-pagination"><button class="button secondary" data-action="history-previous" ${page===0?"disabled":""}>上一頁</button><span class="small muted">${page+1} / ${pageCount}</span><button class="button secondary" data-action="history-next" ${page===pageCount-1?"disabled":""}>下一頁</button></div>`:""}</div></details>`:"";
  return `${heading("每日資產變化，方便回顧。")}<section class="card"><div class="card-header record-actions"><h2>資產曲線</h2><button class="button secondary card-action" data-action="snapshot">${icon("plus")}記錄今天</button></div><p class="chart-current muted small">目前總資產 <span class="mono">${money(p.total)}</span></p>${graph(s.history,175)}<p class="table-note" style="margin-top:20px">開啟 App 時記錄台灣當天的資產；未開啟的日期不會補記。曲線反映資產變化，包含投入與提領，不等同投資報酬率。</p></section><section class="card" style="margin-top:18px"><div class="card-header"><h2>每日紀錄</h2><span class="small muted history-count">最近 ${recent.length} 筆</span></div>${recent.length?historyTable(recent,ordered)+archive:empty("還沒有資產紀錄","新增持倉後，按記錄今天保存目前總額。","","history")}</section>`;
}
function changeHistoryPage(direction){const pages=Math.ceil(Math.max(0,s.history.length-10)/10);s.historyArchivePage=Math.min(Math.max(0,s.historyArchivePage+direction),Math.max(0,pages-1));s.historyArchiveOpen=true;render();}

function installedMode(){return navigator.standalone===true||typeof window.matchMedia==="function"&&window.matchMedia("(display-mode: standalone)").matches;}
function installCard(){return `<section class="card full"><div class="card-header"><h2>加入手機主畫面</h2>${badge(s.demo?"示範預覽":installedMode()?"App 模式":"網頁模式",!s.demo&&installedMode()?"green":"")}</div><p class="small muted">同一個網站、同一份帳號資料。部署後，手機可從主畫面以 App 模式開啟。</p><ol class="install-steps"><li>用 iPhone 的 Safari 開啟正式網站網址。</li><li>按「分享」，選「加入主畫面」。</li><li>若有「打開為網頁 App」，將它開啟，再按「加入」。</li><li>回到主畫面，點 Wealth Tracker 圖示使用。</li></ol>${s.demo?'<p class="callout">目前是示範資料。下載的 HTML 預覽檔只用來看畫面；正式安裝請使用部署後的 HTTPS 網址。</p>':''}</section>`;}
function settingsPage(){return `${heading("目標、資料與分享，都由你決定。")}
  <div class="settings-grid"><section class="card"><div class="card-header"><div><div class="eyebrow">NEXT MILESTONE</div><h2>財務目標</h2></div></div><form id="goalForm" novalidate><label>目標金額（台幣）<input type="number" name="goal" min="1" step="any" value="${esc(s.settings.goal)}" required></label><label>目標日期<input type="date" name="targetDate" value="${esc(s.settings.targetDate)}" required></label><label>每月額外投入（台幣）<input type="number" name="monthly" min="0" step="any" value="${esc(s.settings.monthly)}" required></label><button class="button primary" type="submit">儲存目標</button></form></section>
  <section class="card"><div class="card-header"><div><div class="eyebrow">MARKET DATA</div><h2>美股報價設定</h2></div>${icon("lock")}</div><form id="keyForm"><label>你的 Finnhub API 金鑰<input type="password" name="key" value="${esc(s.settings.finnhubKey)}" autocomplete="off" placeholder="填入你自己的金鑰"></label><p class="callout">美股與朋友的美股估值使用這組金鑰。加密貨幣、台股與匯率使用各自的公開來源；報價時間與延遲依來源而定。金鑰保存在私人設定，不會分享。</p><button class="button secondary" type="submit">儲存金鑰</button></form></section>
  <section class="card"><div class="card-header"><div><div class="eyebrow">YOUR ACCOUNT</div><h2>帳號</h2></div>${badge(s.demo?"示範":"Google 登入")}</div><div class="account-row"><span class="avatar ${googlePhotoUrl(s.user?.photoURL)?"has-photo":""}">${avatarContent()}</span><div><h3>${esc(s.user?.displayName||"使用者")}</h3><p>${esc(s.user?.email||"")}</p></div></div><div class="settings-buttons"><button class="button secondary" data-action="logout">${icon("logout")}登出</button>${!s.demo&&cloud.isAdmin(s.user)?'<button id="adminToggle" class="button secondary" data-action="admin" aria-expanded="false" aria-controls="adminCard">管理使用者</button>':""}</div><section id="adminCard" class="admin-panel hidden" aria-live="polite"></section></section>
  <section class="card"><div class="card-header"><div><div class="eyebrow">KEEP A COPY</div><h2>資料備份</h2></div>${icon("download")}</div><p class="small muted">匯出持倉、策略、目標與歷史紀錄。JSON 可重新匯入；匯出不包含 API 金鑰與分享授權。</p><div class="settings-buttons" style="margin-top:20px"><button class="button secondary" data-action="export-json">JSON 備份</button><button class="button secondary" data-action="export-csv">CSV 持倉</button><button class="button secondary" data-action="import">匯入備份</button></div><input type="file" id="importFile" accept=".json,application/json" class="hidden"><p class="small muted" style="margin-top:18px">新版 ${VERSION} · 每日紀錄以 Asia/Taipei 為準</p></section>${installCard()}</div>`;}

function render(force=false){if(!s.user)return;$("breadcrumb").textContent="我的資產 / "+PAGES[s.page][0];$("localDate").textContent=taipeiDay();$("userAvatar").innerHTML=avatarContent();$("userAvatar").classList.toggle("has-photo",!!googlePhotoUrl(s.user.photoURL));$("navigation").innerHTML=Object.entries(PAGES).map(([key,[title]])=>`<button data-page="${key}" aria-label="${esc(title)}" class="${s.page===key?"active":""}" ${s.page===key?'aria-current="page"':""}>${icon(key)}<span>${key==="assets"?"持倉":key==="sharing"?"共享":key==="history"?"紀錄":title}</span></button>`).join("");$("sidebarStatus").textContent=s.demo?"示範資料":"雲端同步";if(s.page==="settings"&&s.settingsDirty&&!force)return;const renders={home,assets:assetsPage,sharing,history:historyPage,settings:settingsPage};$("content").innerHTML=renders[s.page]();}
function syncSelection(){if(s.shareDirty)return;s.selected=(s.published.assets||[]).map(a=>a.id);s.portfolioViewers=[...(s.published.viewerUids||[])];s.strategyViewers=[...(s.strategyAccess.viewerUids||[])];}
async function setPage(page){if(!PAGES[page])return;if(s.settingsDirty&&page!=="settings"&&!await confirm("離開設定？","未儲存的表單內容會捨棄。","離開"))return;s.settingsDirty=false;s.dirtyForms.clear();s.page=page;location.hash=page;render(true);window.scrollTo({top:0,behavior:"instant"});if(page==="sharing")await loadSharing();}
function confirm(title,text,label="確認"){return new Promise(resolve=>{$("confirmTitle").textContent=title;$("confirmText").textContent=text;$("confirmAction").textContent=label;pendingConfirmation=resolve;$("confirmDialog").showModal();});}
$("confirmAction").onclick=()=>{const fn=pendingConfirmation;pendingConfirmation=null;$("confirmDialog").close();fn?.(true);};
$("confirmDialog").addEventListener("close",()=>{if(pendingConfirmation){pendingConfirmation(false);pendingConfirmation=null;}});

function stopSession(){s.session++;s.assets=[];s.history=[];s.settings={...DEFAULT_SETTINGS};s.published={assets:[],viewerUids:[]};s.strategyAccess={viewerUids:[]};s.friends=[];s.ownPosts=[];s.friendPosts=[];s.invites={sent:[],received:[]};s.friend="self";s.selected=[];s.portfolioViewers=[];s.strategyViewers=[];s.inviteEmail="";s.subscriptions.forEach(fn=>fn());s.subscriptions=[];s.user=null;s.historyArchivePage=0;s.historyArchiveOpen=false;s.refreshing=false;s.settingsDirty=false;s.dirtyForms.clear();s.shareDirty=false;for(const name of ["assetDialog","strategyDialog","confirmDialog"]){if($(name).open)$(name).close();}}
function showLogin(){stopSession();$("appView").classList.add("hidden");$("pendingView").classList.add("hidden");$("loginView").classList.remove("hidden");}
function showApp(){const initial=location.hash.slice(1);s.page=PAGES[initial]?initial:"home";$("loginView").classList.add("hidden");$("pendingView").classList.add("hidden");$("appView").classList.remove("hidden");$("demoBanner").classList.toggle("hidden",!s.demo);render(true);}
async function startUser(user){if(s.demo)return;stopSession();if(!user){showLogin();return;}s.user=user;const session=s.session;$("loginError").textContent="正在確認授權與讀取資料…";try{const status=await cloud.checkAccess(user);if(session!==s.session)return;if(status!=="approved"){$("loginView").classList.add("hidden");$("appView").classList.add("hidden");$("pendingView").classList.remove("hidden");$("pendingMessage").textContent=status==="denied"?"你的使用申請已被拒絕，請聯絡擁有者。":"已送出使用申請。擁有者核准後，按重新檢查即可使用。";return;}const loaded=await cloud.loadUser(user);if(session!==s.session)return;Object.assign(s,loaded);const guard=fn=>(...args)=>{if(session===s.session)fn(...args);};s.lastRefresh=0;syncSelection();showApp();s.subscriptions=cloud.listenUser(user.uid,{assets:guard(assets=>{s.assets=assets;render();}),history:guard(history=>{s.history=history;render();}),settings:guard(settings=>{s.settings=settings;render();}),published:guard(value=>{s.published=value;syncSelection();render();}),strategyAccess:guard(value=>{s.strategyAccess=value;syncSelection();render();}),error:guard(e=>toast(message(e),true))});s.subscriptions.push(...cloud.listenFriends(user.uid,guard(friends=>{s.friends=friends;if(s.friend!=="self"&&!friends.some(f=>f.id===s.friend)){s.friend="self";s.friendPosts=[];}else if(s.friend!=="self"&&!friends.find(f=>f.id===s.friend)?.strategyAccess){s.friendPosts=[];}render();}),guard(e=>toast(message(e),true))));await refreshOwn(false);if(session===s.session)await saveSnapshot(false);if(s.page==="sharing")await loadSharing();}catch(e){if(session!==s.session)return;$("loginError").textContent=message(e);$("loginView").classList.remove("hidden");$("appView").classList.add("hidden");}}
async function initFirebase(){const button=$("loginButton");button.disabled=true;button.textContent="正在連線…";try{await Promise.race([cloud.connect(),new Promise((_,reject)=>setTimeout(()=>reject(new Error("連線逾時，請重新嘗試或先看示範版。")),15000))]);firebaseReady=true;authUnsubscribe?.();authUnsubscribe=cloud.watchAuth(startUser);button.textContent="使用 Google 登入";}catch(e){$("loginError").textContent=message(e);button.textContent="重新連線";}finally{button.disabled=false;}}
$("loginButton").onclick=()=>task($("loginButton"),async()=>{if(!firebaseReady)return initFirebase();await cloud.login();},$("loginError"));
$("demoButton").onclick=()=>startDemo();

function demoData(){const now=new Date().toISOString(),fx=32.1;const asset=(name,mode,symbol,qty,costPer,price,costFx=32.4)=>({id:id(),name,mode,symbol,qty,costPer,costFx,type:TYPES[mode],quote:{nativePrice:price,fx:mode==="tw"?1:fx,currency:mode==="tw"?"TWD":"USD",source:"示範行情",priceAt:now,fetchedAt:now,fxAt:now,lastAttemptAt:now,error:""},updatedAt:now});const assets=[asset("Apple","stock","AAPL",28,175,194.6),asset("Bitcoin","crypto","BTC",.18,65000,72000),asset("元大台灣50","tw","0050",1200,48,52.4,null),asset("Ethereum","crypto","ETH",3.5,2600,2950),asset("美元現金","usd",null,4500,4500,1),{id:id(),name:"生活備用金",mode:"manual",type:"現金",value:180000,cost:null,updatedAt:now}];const total=portfolio(assets).total;const history=Array.from({length:14},(_,i)=>({date:taipeiDay(new Date(Date.now()-(13-i)*86400000)),total:Math.round(total*(.84+i*.012+Math.sin(i*1.5)*.018))}));history.at(-1).total=total;const friends=[{id:"demo-friend",ownerName:"柏宇",assets:[asset("Vanguard 全市場 ETF","stock","VTI",32,230,285),asset("Solana","crypto","SOL",12,165,148)],updatedAt:now,portfolioAccess:true,strategyAccess:true}];const post={id:id(),title:"分批累積指數 ETF",symbol:"0050",term:"long",thesis:"以分散持有與固定投入，建立長期部位。\n每次投入維持相近金額，定期檢視資產配置。",entry:"每月固定投入，保留生活備用金。",invalidation:"現金需求改變，或原本的資產配置不再適合。",target:"持有三年以上，每季檢視一次。",status:"active",published:true,createdAt:now,updatedAt:now};friends[0].demoPosts=[{...post,id:id(),symbol:"VTI",title:"維持核心部位，定期再平衡"}];return {assets,history,friends,ownPosts:[post,{...post,id:id(),title:"等待區間突破後的回測",symbol:"BTC",term:"short",thesis:"先觀察成交量與價格反應，確認條件再執行。",entry:"突破區間後回測不破，且出現向上的量價延續。",invalidation:"重新跌回原區間，或回測時賣壓擴大。",target:"依執行時的風險報酬設定，不預先追價。",status:"watching",published:false}],friendPosts:[{...post,id:id(),symbol:"VTI",title:"維持核心部位，定期再平衡"}],settings:{...DEFAULT_SETTINGS,goal:3000000,monthly:15000,finnhubKey:""},published:{ownerName:"小陽",assets:assets.slice(0,3).map(sharedAsset),viewerUids:["demo-friend"],updatedAt:now},strategyAccess:{viewerUids:["demo-friend"]},invites:{sent:[{id:"demo-invite",ownerUid:"demo-self",recipientEmail:"boyu@example.com",viewerUid:"demo-friend",status:"accepted"}],received:[]}};}
function startDemo(){stopSession();s.search="";s.filter="all";s.sort="value";s.demo=true;s.user={uid:"demo-self",displayName:"小陽",email:"demo@example.com",emailVerified:true};Object.assign(s,demoData());s.shareDirty=false;s.settingsDirty=false;s.friend="self";s.sharingTab="portfolios";s.lastRefresh=0;syncSelection();showApp();}

async function refreshOwn(notify=true){if(s.refreshing)return;const user=s.user,session=s.session;if(!user)return;s.refreshing=true;render();try{if(s.demo){const now=new Date().toISOString();s.assets=s.assets.map(a=>a.mode==="manual"?a:{...a,quote:{...a.quote,fetchedAt:now,priceAt:now,error:""}});s.lastRefresh=Date.now();if(notify)toast("示範行情已更新；金額不是即時報價。");}else{const result=await refreshMarket(s.assets,s.settings.finnhubKey);if(session!==s.session)return;const applied=await cloud.saveQuotes(user.uid,result.updates,result.fx);if(session!==s.session)return;const updates=new Map(applied.map(a=>[a.id,a]));s.assets=s.assets.map(a=>{const u=updates.get(a.id);return u&&a.mode===u.mode&&a.symbol===u.symbol?{...a,quote:u.quote}:a;});s.lastRefresh=Date.now();if(result.issues.length)toast(result.issues.join("\n"),true);else if(notify)toast("已更新可取得的行情。");}}finally{if(session===s.session){s.refreshing=false;render();}}}
async function refreshFriend(){if(s.refreshing)return;const friend=s.friends.find(f=>f.id===s.friend);if(!friend)return;const session=s.session;s.refreshing=true;render();try{if(!s.demo){const result=await refreshMarket(friend.assets,s.settings.finnhubKey);if(session!==s.session)return;const map=new Map(result.updates.map(u=>[u.id,u.quote]));friend.assets=friend.assets.map(a=>map.has(a.id)?{...a,quote:map.get(a.id)}:a);if(result.issues.length)toast(result.issues.join("\n"),true);}else toast("示範行情已更新，未修改朋友的持倉。");friend.localRefreshed=new Date().toISOString();friend.lastRefresh=Date.now();}finally{if(session===s.session){s.refreshing=false;render();}}}
async function saveSnapshot(overwrite=true){if(!s.assets.length)return;const date=taipeiDay(),total=portfolio(s.assets).total;if(s.demo){const previous=s.history.find(h=>h.date===date);if(previous){if(overwrite)previous.total=total;}else s.history.push({date,total});s.history.sort((a,b)=>a.date.localeCompare(b.date));}else await cloud.snapshot(s.user.uid,date,total,overwrite);if(overwrite)toast("已記錄台灣今天的資產。");render();}

function openAsset(assetId=null){editingAsset=assetId?s.assets.find(a=>a.id===assetId):null;const f=$("assetForm");f.reset();f.elements.mode.value=editingAsset?.mode||"stock";for(const name of ["name","symbol","qty","value","cost","costPer","costFx","type"]){if(editingAsset?.[name]!=null)f.elements[name].value=editingAsset[name];}f.elements.summary.value=editingAsset?.isSummary?"yes":"no";$("assetDialogTitle").textContent=editingAsset?"編輯持倉":"新增持倉";$("assetError").textContent="";setAssetMode();$("assetDialog").showModal();}
function setAssetMode(){const mode=$("assetForm").elements.mode.value;const manual=mode==="manual",usd=mode==="usd",tw=mode==="tw";for(const [name,hide] of [["symbolField",manual||usd],["quantityField",manual],["valueField",!manual],["nativeCostField",manual],["manualCostField",!manual],["costFxField",manual||tw],["typeField",!manual],["summaryField",!usd]])$(name).classList.toggle("hidden",hide);$("quantityLabel").textContent=usd?"目前美元金額":mode==="crypto"?"持有數量":"持有股數";$("nativeCostLabel").textContent=usd?"本金（美元總額）":tw?"平均買入價（台幣／股）":mode==="crypto"?"平均買入價（USD／顆）":"平均買入價（USD／股）";const hints={stock:"美股需在設定填入 Finnhub 金鑰。買入匯率留空時，損益只反映美元價差。",crypto:"常見幣種可填 BTC、ETH 等代號。代號有重複時，改填 CoinGecko ID。",tw:"台股與 ETF 使用收盤價，並非盤中即時行情。",usd:"已列出個股時，請只把美元現金計入總資產；帳戶總值可設為參考。",manual:"輸入台幣現值；本金選填，未填不會把損益當成零。"};$("assetModeHint").textContent=hints[mode];}
$("assetForm").elements.mode.onchange=setAssetMode;
$("assetForm").onsubmit=e=>{e.preventDefault();const f=e.currentTarget;task(f.querySelector('[type="submit"]'),async()=>{const session=s.session;const fields=Object.fromEntries(new FormData(f));fields.isSummary=fields.summary==="yes";let a=parseAsset(fields,editingAsset);if(!s.demo)a=await cloud.saveAsset(s.user.uid,a,editingAsset?(editingAsset.updatedAt??null):undefined);if(session!==s.session)return;const index=s.assets.findIndex(x=>x.id===a.id);if(index>=0)s.assets[index]=a;else s.assets.push(a);if(s.demo&&s.published.assets.some(x=>x.id===a.id))s.published.assets=s.published.assets.map(x=>x.id===a.id?sharedAsset(a):x);$("assetDialog").close();render(true);toast("持倉已儲存。");if(a.mode!=="manual"){s.lastRefresh=0;await refreshOwn(false);}},$("assetError"));};
function openStrategy(postId=null){editingPost=postId?s.ownPosts.find(p=>p.id===postId):null;const f=$("strategyForm");f.reset();f.elements.term.value=s.sharingTab==="short"?"short":"long";for(const name of ["title","symbol","term","thesis","entry","invalidation","target","status"]){if(editingPost?.[name]!=null)f.elements[name].value=editingPost[name];}f.elements.published.checked=editingPost?.published||false;$("strategyDialogTitle").textContent=editingPost?"編輯交易策略":"新增交易策略";$("strategyError").textContent="";$("strategyDialog").showModal();}
$("strategyForm").onsubmit=e=>{e.preventDefault();const f=e.currentTarget;task(f.querySelector('[type="submit"]'),async()=>{const session=s.session;const data=Object.fromEntries(new FormData(f));for(const key of ["title","symbol","thesis"]){if(!data[key]?.trim())throw new Error("請填策略名稱、標的與交易理由。");}const now=new Date().toISOString();const post={id:editingPost?.id||id(),ownerUid:s.user.uid,ownerName:s.user.displayName,title:data.title.trim(),symbol:data.symbol.trim().toUpperCase(),term:data.term,thesis:data.thesis.trim(),entry:data.entry.trim(),invalidation:data.invalidation.trim(),target:data.target.trim(),status:data.status,published:f.elements.published.checked,createdAt:editingPost?.createdAt||now,updatedAt:now};if(!s.demo)await cloud.saveStrategy(s.user.uid,post);if(session!==s.session)return;const index=s.ownPosts.findIndex(p=>p.id===post.id);if(index>=0)s.ownPosts[index]=post;else s.ownPosts.push(post);s.sharingTab=post.term;$("strategyDialog").close();render(true);toast(post.published?"策略已儲存並分享給策略授權名單。":"已儲存私人草稿。");},$("strategyError"));};

async function loadSharing(){if(s.demo){const friend=s.friends.find(f=>f.id===s.friend);s.friendPosts=friend?.demoPosts||[];render();return;}const session=s.session;const [invites,posts]=await Promise.all([cloud.invitations(s.user),cloud.strategies(s.user.uid,true)]);if(session!==s.session)return;s.invites=invites;s.ownPosts=posts;const friend=s.friends.find(f=>f.id===s.friend);const friendId=s.friend,friendPosts=friend?.strategyAccess?await cloud.strategies(friend.id):[];if(session===s.session&&s.friend===friendId){s.friendPosts=friendPosts;render();}}
async function publish(){if(s.selected.length>100)throw new Error("每次最多分享 100 筆持倉。");if(s.demo){s.published={ownerName:s.user.displayName,assets:s.assets.filter(a=>s.selected.includes(a.id)).map(sharedAsset),viewerUids:[...s.portfolioViewers],updatedAt:new Date().toISOString()};s.strategyAccess={viewerUids:[...s.strategyViewers]};}else await cloud.publish(s.user.uid,s.user.displayName||"使用者",s.selected,s.portfolioViewers,s.strategyViewers);s.shareDirty=false;toast("分享設定已儲存。");render(true);}
async function admin(button=null,reload=false){const card=$("adminCard");if(!card)return;const trigger=button?.dataset.action==="admin"?button:null,opened=trigger?trigger.getAttribute("aria-expanded")==="true":!card.classList.contains("hidden");if(!reload&&opened){card.classList.add("hidden");trigger?.setAttribute("aria-expanded","false");if(trigger)trigger.textContent="管理使用者";return;}card.classList.remove("hidden");trigger?.setAttribute("aria-expanded","true");if(trigger)trigger.textContent="收合名單";if(!reload&&card.dataset.loaded==="true")return;if(adminRequest)return adminRequest;const request=(async()=>{card.innerHTML='<p class="small muted admin-loading" role="status">正在載入使用者名單…</p>';try{const users=s.demo?[]:await cloud.adminUsers();const current=$("adminCard");if(!current)return;current.innerHTML=`<div class="admin-heading"><h3>使用者授權</h3><span class="small muted">App 使用資格，與分享權限分開</span></div>${users.map(u=>`<div class="admin-row"><div>${esc(u.name||"使用者")} ${badge({pending:"待核准",approved:"已核准",denied:"已拒絕"}[u.status]||u.status)}<div class="small muted">${esc(u.email)}</div></div><div class="admin-actions"><button class="button secondary" data-action="approve" data-id="${esc(u.id)}">核准</button><button class="button danger" data-action="deny" data-id="${esc(u.id)}">拒絕</button></div></div>`).join("")||'<p class="small muted">目前沒有使用者申請。</p>'}`;current.dataset.loaded="true";}catch(error){const current=$("adminCard");if(current)current.innerHTML=`<p class="small muted" role="alert">載入失敗：${esc(error?.message||"請稍後重試")}</p><button class="button secondary" data-action="admin-reload">重新載入</button>`;toast(message(error),true);}finally{adminRequest=null;}})();adminRequest=request;return request;}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportJson(){const session=s.session;if(!s.demo){const posts=await cloud.strategies(s.user.uid,true);if(session!==s.session)return;s.ownPosts=posts;}download("wealth-backup-"+taipeiDay()+".json",JSON.stringify(buildBackup(s),null,2),"application/json");toast("已匯出備份，不含金鑰與分享授權。");}
function exportCsv(){const cell=value=>'"'+String(value??"").replace(/"/g,'""')+'"';const rows=[["名稱","類別","代號","數量","台幣市值","台幣損益","損益百分比","計算口徑","行情時間","參考值"]];for(const a of s.assets){const v=valuation(a);rows.push([a.name,TYPES[a.mode],a.symbol,a.qty,v.value,v.pnl,v.percent,v.kind,a.quote?.priceAt||a.quote?.fetchedAt,a.isSummary?"是":"否"]);}download("wealth-holdings-"+taipeiDay()+".csv","\ufeff"+rows.map(row=>row.map(cell).join(",")).join("\r\n"),"text/csv;charset=utf-8");}
async function importFile(file){const session=s.session,user=s.user,demo=s.demo;if(file.size>2*1024*1024)throw new Error("備份檔案超過 2 MB，請先確認內容。");const data=parseBackup(JSON.parse(await file.text()));if(session!==s.session)return;const {assets,history,settings,strategies}=data;if(!await confirm("匯入備份？",`將新增 ${assets.length} 筆持倉、${strategies.length} 份私人策略草稿，並補上尚未存在的日期。${settings?"財務目標會改用備份設定。":""}請避免匯入重複持倉。`,"匯入"))return;if(session!==s.session)return;for(const a of assets){if(!demo)await cloud.saveAsset(user.uid,a);if(session!==s.session)return;s.assets.push(a);}for(const h of history){if(s.history.some(x=>x.date===h.date))continue;if(!demo)await cloud.snapshot(user.uid,h.date,h.total,false);if(session!==s.session)return;s.history.push(h);}for(const draft of strategies){const post={...draft,ownerUid:user.uid,ownerName:user.displayName||"使用者"};if(!demo)await cloud.saveStrategy(user.uid,post);if(session!==s.session)return;s.ownPosts.push(post);}if(settings){if(!demo)await cloud.saveSettings(user.uid,settings);if(session!==s.session)return;s.settings={...s.settings,...settings};}s.history.sort((a,b)=>a.date.localeCompare(b.date));render(true);toast("備份已匯入；還原策略為私人草稿，分享設定由你選擇。");}

document.addEventListener("click",async e=>{const button=e.target.closest("button");if(!button)return;if(button.dataset.close){$(button.dataset.close).close();return;}if(button.dataset.page){await task(null,()=>setPage(button.dataset.page));return;}if(button.dataset.tab){s.sharingTab=button.dataset.tab;render(true);return;}const action=button.dataset.action;if(!action)return;await task(button,async()=>{
  if(action==="account")return setPage("settings");
  if(action==="history-previous"||action==="history-next")return changeHistoryPage(action==="history-next"?1:-1);
  if(action==="add-asset")return openAsset();if(action==="edit-asset")return openAsset(button.dataset.id);
  if(action==="delete-asset"){const a=s.assets.find(a=>a.id===button.dataset.id);if(!await confirm("刪除這個持倉？",`「${a.name}」也會從已分享的持倉移除。`,"刪除"))return;if(!s.demo)await cloud.deleteAsset(s.user.uid,a.id);s.assets=s.assets.filter(x=>x.id!==a.id);s.published.assets=s.published.assets.filter(x=>x.id!==a.id);s.selected=s.selected.filter(x=>x!==a.id);render(true);return toast("已刪除持倉。");}
  if(action==="refresh")return refreshOwn();if(action==="refresh-friend")return refreshFriend();if(action==="snapshot")return saveSnapshot();
  if(action==="add-strategy")return openStrategy();if(action==="edit-strategy")return openStrategy(button.dataset.id);
  if(action==="delete-strategy"){if(!await confirm("刪除策略？","策略將從草稿與朋友的共享頁移除。","刪除"))return;if(!s.demo)await cloud.deleteStrategy(s.user.uid,button.dataset.id);s.ownPosts=s.ownPosts.filter(p=>p.id!==button.dataset.id);render(true);return toast("策略已刪除。");}
  if(action==="publish")return publish();if(action==="reload-sharing")return loadSharing();
  if(action==="revoke"){if(!await confirm("撤銷這位朋友的授權？","將停止持倉與策略的新讀取；已查看的內容無法收回。","撤銷"))return;const uid=button.dataset.id;if(!s.demo)await cloud.revoke(s.user.uid,uid);s.portfolioViewers=s.portfolioViewers.filter(x=>x!==uid);s.strategyViewers=s.strategyViewers.filter(x=>x!==uid);s.published.viewerUids=s.published.viewerUids.filter(x=>x!==uid);s.strategyAccess.viewerUids=s.strategyAccess.viewerUids.filter(x=>x!==uid);s.shareDirty=false;render(true);return toast("已撤銷授權。");}
  if(action==="accept-invite"){if(!s.demo)await cloud.acceptInvite(s.user,button.dataset.id);return loadSharing();}
  if(action==="cancel-invite"){if(!s.demo)await cloud.removeInvite(button.dataset.id);else s.invites.sent=s.invites.sent.filter(x=>x.id!==button.dataset.id);return loadSharing();}
  if(action==="admin"){admin(button);return;}if(action==="admin-reload"){admin(null,true);return;}if(action==="approve"||action==="deny"){await cloud.setAccess(button.dataset.id,action==="approve"?"approved":"denied");return admin(button,true);}
  if(action==="export-json")return exportJson();if(action==="export-csv")return exportCsv();if(action==="import")return $("importFile").click();
  if(action==="recheck")return startUser(s.user);
  if(action==="logout"||action==="exit-demo"){const demo=s.demo;s.demo=false;showLogin();if(!demo)await cloud.logout();else if(!firebaseReady)await initFirebase();return;}
});});
document.addEventListener("toggle",e=>{if(e.target.id==="olderHistory"&&e.target.isConnected)s.historyArchiveOpen=e.target.open;},true);
document.addEventListener("input",e=>{if(e.target.id==="assetSearch"){s.search=e.target.value;$("assetRows").innerHTML=assetRows(filteredAssets());}const dirtyForm=e.target.closest("#goalForm,#keyForm");if(dirtyForm){s.dirtyForms.add(dirtyForm.id);s.settingsDirty=true;}if(e.target.closest("#inviteForm"))s.inviteEmail=e.target.value;});
document.addEventListener("change",e=>{const el=e.target;for(const [key,target] of [["shareAsset","selected"],["portfolioViewer","portfolioViewers"],["strategyViewer","strategyViewers"]])if(el.dataset[key]){const value=el.dataset[key];s[target]=el.checked?[...new Set([...s[target],value])]:s[target].filter(x=>x!==value);s.shareDirty=true;}if(el.id==="assetFilter"){s.filter=el.value;$("assetRows").innerHTML=assetRows(filteredAssets());}if(el.id==="assetSort"){s.sort=el.value;$("assetRows").innerHTML=assetRows(filteredAssets());}if(el.id==="friendSelect"){s.friend=el.value;s.friendPosts=[];render(true);task(null,()=>loadSharing());}if(el.id==="importFile"&&el.files[0])task(null,()=>importFile(el.files[0]));});
document.addEventListener("submit",e=>{const form=e.target;if(["assetForm","strategyForm"].includes(form.id))return;if(!["goalForm","keyForm","inviteForm"].includes(form.id))return;e.preventDefault();task(form.querySelector('[type="submit"]'),async()=>{const fields=Object.fromEntries(new FormData(form));if(form.id==="goalForm"){const goal=Number(fields.goal),monthly=Number(fields.monthly);if(!fields.goal||!finite(goal)||goal<=0||!fields.monthly||!finite(monthly)||monthly<0||!/^\d{4}-\d{2}-\d{2}$/.test(fields.targetDate)||!finite(new Date(fields.targetDate).getTime()))throw new Error("請填有效的目標金額、日期與非負投入金額。");const settings={...s.settings,goal,monthly,targetDate:fields.targetDate};if(!s.demo)await cloud.saveSettings(s.user.uid,{goal,monthly,targetDate:fields.targetDate});s.settings=settings;s.dirtyForms.delete(form.id);s.settingsDirty=s.dirtyForms.size>0;toast("財務目標已更新。");render();}if(form.id==="keyForm"){const settings={...s.settings,finnhubKey:fields.key.trim()};if(!s.demo)await cloud.saveSettings(s.user.uid,{finnhubKey:settings.finnhubKey});s.settings=settings;s.dirtyForms.delete(form.id);s.settingsDirty=s.dirtyForms.size>0;toast("私人金鑰已儲存。");render();}if(form.id==="inviteForm"){const email=fields.email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email===s.user.email.toLowerCase())throw new Error("請填朋友的有效 Google 帳號，不能邀請自己。");if(s.invites.sent.some(i=>i.recipientEmail===email))throw new Error("這個帳號已在邀請名單中。");if(s.demo)s.invites.sent.push({id:id(),recipientEmail:email,status:"pending",ownerUid:s.user.uid});else await cloud.invite(s.user.uid,email,s.user.displayName);s.inviteEmail="";toast("邀請已建立；對方登入後可接受。");await loadSharing();}});});
window.addEventListener("hashchange",()=>{const page=location.hash.slice(1);if(s.user&&PAGES[page]&&page!==s.page)setPage(page).catch(e=>toast(message(e),true));});
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
if(new URLSearchParams(location.search).has("demo"))startDemo();else initFirebase();
