import * as cloud from "./store.js";
import {NOTIFICATION_WORKER_URL,FIREBASE_VAPID_KEY} from "./config.js";
import {taipeiDay} from "./core.js";
const PREF_KEY="wealthTrackerNotificationPrefs",TOKEN_KEY="wealthTrackerPushToken",DEVICE_KEY="wealthTrackerPushDevice",OPENED_KEY="wealthTrackerNotificationOpenedDay";
const scoped=key=>key+":"+cloud.currentUserId();
const configured=()=>Boolean(NOTIFICATION_WORKER_URL&&FIREBASE_VAPID_KEY);
const prefs=()=>{try{return {strategy:true,daily:true,...JSON.parse(localStorage.getItem(scoped(PREF_KEY))||"{}")}}catch{return {strategy:true,daily:true}}};
function savePrefs(value){localStorage.setItem(scoped(PREF_KEY),JSON.stringify(value));}
function deviceId(){const key=scoped(DEVICE_KEY);let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id);}return id;}
async function request(path,body){const idToken=await cloud.currentIdToken();if(!idToken)throw new Error("登入狀態已失效，請重新登入。");const response=await fetch(new URL(path,NOTIFICATION_WORKER_URL),{method:"POST",headers:{Authorization:"Bearer "+idToken,"Content-Type":"application/json"},body:JSON.stringify(body)});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||"通知服務暫時無法使用。");return data;}
async function getToken(){const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent||""),standalone=navigator.standalone===true||window.matchMedia?.("(display-mode: standalone)").matches;if(ios&&!standalone)throw new Error("iPhone／iPad 請先在 Safari 選「加入主畫面」，再從主畫面開啟 App 啟用通知。");if(!("Notification"in window)||!("serviceWorker"in navigator))throw new Error("這個瀏覽器不支援手機通知。");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("你尚未允許通知；可到手機設定中開啟。");const registration=await navigator.serviceWorker.ready,token=await cloud.pushToken(registration,FIREBASE_VAPID_KEY);if(!token)throw new Error("未取得手機通知識別碼，請重新嘗試。");return token;}
export function notificationStatus(){return {configured:configured(),permission:("Notification"in window)?Notification.permission:"unsupported",prefs:prefs(),subscribed:Boolean(localStorage.getItem(scoped(TOKEN_KEY)))};}
export async function enableNotifications(){if(!configured())throw new Error("通知服務尚未部署完成。需要先完成 Cloudflare Worker 與 Firebase 推播金鑰設定。");const token=await getToken(),settings=prefs();await request("/register",{token,deviceId:deviceId(),...settings});localStorage.setItem(scoped(TOKEN_KEY),token);savePrefs(settings);await request("/heartbeat",{deviceId:deviceId()});localStorage.setItem(scoped(OPENED_KEY),taipeiDay());return settings;}
export async function updateNotificationPreferences(strategy,daily){const next={strategy:Boolean(strategy),daily:Boolean(daily)};const token=localStorage.getItem(scoped(TOKEN_KEY));if(configured()&&token)await request("/register",{token,deviceId:deviceId(),...next});savePrefs(next);return next;}
export async function disableNotifications(){let failure=null;if(configured()){try{await request("/delete",{deviceId:deviceId()})}catch(error){failure=error}}await cloud.removePushToken().catch(()=>{});localStorage.removeItem(scoped(TOKEN_KEY));savePrefs({strategy:false,daily:false});if(failure)throw failure;}
export async function appOpened(){const day=taipeiDay();if(!configured()||!localStorage.getItem(scoped(TOKEN_KEY))||localStorage.getItem(scoped(OPENED_KEY))===day||!("Notification"in window)||Notification.permission!=="granted")return;try{const registration=await navigator.serviceWorker.ready,token=await cloud.pushToken(registration,FIREBASE_VAPID_KEY),settings=prefs();if(token){localStorage.setItem(scoped(TOKEN_KEY),token);await request("/register",{token,deviceId:deviceId(),...settings});}await request("/heartbeat",{deviceId:deviceId()});localStorage.setItem(scoped(OPENED_KEY),day)}catch{}}
export async function strategyPublished(post){if(!post?.published)return null;if(!configured())throw new Error("通知服務尚未完成設定。");const result=await request("/strategy-event",{postId:post.id});if(result.failed>0)throw new Error(result.errors?.[0]||"部分裝置通知傳送失敗，請稍後重新儲存策略。");return result;}
