import {createReview,castReviewVote} from './review.js';
// Use the app's already authenticated SDK; do not create a second auth session.
export function reviewRepository(sdk,db){
  const doc=(...p)=>sdk.doc(db,...p),head=(uid,id)=>doc('strategyReviews',uid,'posts',id),round=(uid,id,r)=>doc('strategyReviews',uid,'posts',id,'rounds',r),teacher=(uid,id)=>doc('strategyReviews',uid,'posts',id,'teacher','current');
  async function context(tx,uid,id){const [post,access]=await Promise.all([tx.get(doc('strategies',uid,'posts',id)),tx.get(doc('strategyAccess',uid))]);if(!post.exists())throw new Error('策略已刪除。');return {post:post.data(),viewers:access.data()?.viewerUids||[]};}
  return {
    async load(uid,id){const [h,a,t]=await Promise.all([sdk.getDoc(head(uid,id)),sdk.getDoc(doc('strategyAccess',uid)),sdk.getDoc(teacher(uid,id))]);const currentViewers=a.data()?.viewerUids||[];if(!h.exists())return {currentViewers,teacherDecision:t.exists()?t.data():null};const r=await sdk.getDoc(round(uid,id,h.data().roundId));return r.exists()?{...r.data(),currentViewers,teacherDecision:t.exists()?t.data():null}:{currentViewers,teacherDecision:t.exists()?t.data():null};},
    async start(uid,id,voters,deadlineMs,roundId){return sdk.runTransaction(db,async tx=>{const c=await context(tx,uid,id);const r=createReview(c.post,voters,c.viewers,deadlineMs,roundId);await tx.get(head(uid,id));tx.set(round(uid,id,roundId),r);tx.set(head(uid,id),{roundId,strategyUpdatedAt:c.post.updatedAt});return {...r,currentViewers:c.viewers};});},
    async vote(ownerUid,id,roundId,uid,choice,reason,profile){return sdk.runTransaction(db,async tx=>{const c=await context(tx,ownerUid,id);const [h,r]=await Promise.all([tx.get(head(ownerUid,id)),tx.get(round(ownerUid,id,roundId))]);if(h.data()?.roundId!==roundId||!r.exists())throw new Error('本輪投票已被新版取代，請重新整理。');const next=castReviewVote(r.data(),c.post,c.viewers,uid,choice,reason,profile);tx.update(round(ownerUid,id,roundId),{choices:next.choices,reasons:next.reasons,voterProfiles:next.voterProfiles});return {...next,currentViewers:c.viewers};});},
    async submitTeacher(uid,id,profile,reason=''){return sdk.runTransaction(db,async tx=>{const c=await context(tx,uid,id);if(!c.post.published)throw new Error('只有已發布的策略可以送老師審核。');const ref=teacher(uid,id),snap=await tx.get(ref),existing=snap.exists()?snap.data():null;if(existing?.decision==='pending'&&existing.strategyUpdatedAt===c.post.updatedAt)throw new Error('這份策略已在等待老師審核。');const value={decision:'pending',submittedBy:profile.uid,submitterName:String(profile.displayName||'使用者').slice(0,80),reason:String(reason||'').trim().slice(0,500),strategyUpdatedAt:c.post.updatedAt,submittedMs:Date.now(),reviewerUid:'',reviewerName:'',reviewerPhotoURL:'',decidedMs:0};tx.set(ref,value);return value;});},
    async decideTeacher(uid,id,decision,profile,reason=''){return sdk.runTransaction(db,async tx=>{const c=await context(tx,uid,id),ref=teacher(uid,id),snap=await tx.get(ref);if(!snap.exists()||snap.data().decision!=='pending'||snap.data().strategyUpdatedAt!==c.post.updatedAt)throw new Error('這份送審資料已處理或策略已更新，請重新整理。');if(!c.post.published)throw new Error('策略已取消分享。');if(!['approved','returned'].includes(decision))throw new Error('請選擇核准或退回。');const value={...snap.data(),decision,reviewerUid:profile.uid,reviewerName:String(profile.displayName||'老師').slice(0,80),reviewerPhotoURL:String(profile.photoURL||'').slice(0,500),reason:String(reason||'').trim().slice(0,500),decidedMs:Date.now()};tx.set(ref,value);return value;});},
    async history(uid,id){const result=await sdk.getDocs(sdk.collection(db,'strategyReviews',uid,'posts',id,'rounds'));return result.docs.map(x=>x.data()).sort((a,b)=>b.createdMs-a.createdMs);}
  };
}
