import test from 'node:test';
import assert from 'node:assert/strict';
import {createReview,castReviewVote,reviewState,teacherDecisionState} from '../review.js';
const now=1700000000000,post={id:'p',ownerUid:'o',published:true,updatedAt:'v1'},viewers=['a','b'];
const fresh=()=>createReview(post,viewers,viewers,now+10000,'r1',now);
test('every authorized member is included and strategy changes invalidate a poll',()=>{const r=fresh();assert.equal(reviewState(r,post,viewers,now).state,'voting');assert.equal(r.voterUids.length,2);assert.throws(()=>createReview(post,[],viewers,now+1000,'r',now));assert.throws(()=>createReview({...post,published:false},viewers,viewers,now+1000,'r',now));assert.throws(()=>createReview(post,['o'],['o'],now+1000,'r',now));assert.throws(()=>createReview(post,['stranger'],viewers,now+1000,'r',now));assert.equal(reviewState(r,{...post,updatedAt:'v2'},viewers,now).state,'changed');assert.equal(reviewState(r,{...post,published:false},viewers,now).state,'private');assert.equal(reviewState(r,post,['a'],now).state,'revoked');});
test('votes tally by majority at cutoff; ties stay ties and voting is editable before cutoff',()=>{const source=fresh();let r=castReviewVote(source,post,viewers,'a','agree','',{displayName:'A',photoURL:'https://lh3.googleusercontent.com/a'},now);assert.equal(reviewState(r,post,viewers,now).state,'voting');assert.equal(r.voterProfiles.a.displayName,'A');r=castReviewVote(r,post,viewers,'a','reject','改變判斷',{},now);assert.equal(reviewState(r,post,viewers,now).state,'voting');r=castReviewVote(r,post,viewers,'b','agree','',{},now);assert.equal(reviewState(r,post,viewers,now+10001).state,'tie');r=castReviewVote(r,post,viewers,'b','reject','',{},now);assert.equal(reviewState(r,post,viewers,now+10001).state,'rejected');assert.deepEqual(source.choices,{});assert.throws(()=>castReviewVote(r,post,viewers,'a','agree','',{},now+10001));assert.throws(()=>castReviewVote(fresh(),post,viewers,'x','agree','',{},now));assert.throws(()=>castReviewVote(fresh(),post,viewers,'a','invalid','',{},now));assert.throws(()=>castReviewVote(fresh(),post,viewers,'a','agree','x'.repeat(501),{},now));});
test('teacher decision belongs to an explicit submission flow and expires when strategy changes',()=>{assert.equal(teacherDecisionState({decision:'pending',strategyUpdatedAt:'v1'},post),'pending');const decision={decision:'approved',strategyUpdatedAt:'v1'};assert.equal(teacherDecisionState(decision,post),'approved');assert.equal(teacherDecisionState({decision:'returned',strategyUpdatedAt:'v1'},post),'returned');assert.equal(teacherDecisionState(decision,{...post,updatedAt:'v2'}),'outdated');assert.equal(teacherDecisionState(null,post),'none');});
test('new round starts with no votes and deadlines are bounded',()=>{const r=fresh();r.choices.a='agree';const next=createReview({...post,updatedAt:'v2'},viewers,viewers,now+1000,'r2',now);assert.deepEqual(next.choices,{});assert.equal(r.choices.a,'agree');assert.throws(()=>createReview(post,viewers,viewers,now,'r',now));assert.throws(()=>createReview(post,viewers,viewers,now+31*86400000,'r',now));});
