import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {normalizeAsset,sharedAsset} from '../core.js';
const source=fs.readFileSync(new URL('../store.js',import.meta.url),'utf8').replace(/^import .*;\s*$/gm,'').replace(/^export /gm,'').replace('let sdk,db,auth;','let sdk=__sdk,db={},auth={};');
function harness(seed={}){
  const docs=new Map(Object.entries(structuredClone(seed))),deleted=Symbol('delete');
  const snap=ref=>({id:ref.split('/').at(-1),exists:()=>docs.has(ref),data:()=>structuredClone(docs.get(ref))});
  const merge=(a,b)=>{const out={...a};for(const [k,v] of Object.entries(b)){if(v===deleted)delete out[k];else out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(out[k]||{},v):structuredClone(v);}return out;};
  const sdk={doc:(_,...parts)=>parts.join('/'),collection:(_,...parts)=>parts.join('/'),deleteField:()=>deleted,getDoc:async ref=>snap(ref),getDocs:async ref=>({docs:[...docs.keys()].filter(k=>k.startsWith(ref+'/')&&k.slice(ref.length+1).split('/').length===1).map(snap)}),
    runTransaction:async(_,fn)=>{const writes=[];let writing=false;const tx={get:async ref=>{assert.equal(writing,false,'transaction reads must precede writes');return snap(ref);},set:(ref,data,options)=>{writing=true;writes.push(()=>docs.set(ref,options?.merge?merge(docs.get(ref),data):structuredClone(data)));},update:(ref,patch)=>{writing=true;writes.push(()=>{const next={...docs.get(ref)};for(const [field,value] of Object.entries(patch)){const parts=field.split('.');let target=next;for(const part of parts.slice(0,-1)){target[part]={...target[part]};target=target[part];}if(value===deleted)delete target[parts.at(-1)];else target[parts.at(-1)]=structuredClone(value);}docs.set(ref,next);});},delete:ref=>{writing=true;writes.push(()=>docs.delete(ref));}};const result=await fn(tx);for(const write of writes)write();return result;}};
  const context={__sdk:sdk,normalizeAsset,sharedAsset,crypto:webcrypto,structuredClone,console,DEFAULT_SETTINGS:{goal:10000000,targetDate:'2030-05-17',monthly:0,finnhubKey:''},ADMIN_EMAIL:'admin@example.com'};
  const api=vm.runInNewContext(source+'\n({saveAsset,saveQuotes,deleteAsset,publish,loadUser,snapshot});',context);
  return {api,docs};
}
const asset={id:'a',name:'Stock',mode:'stock',symbol:'TEST',qty:10,costPer:100,updatedAt:'one',quote:{nativePrice:110,fx:32,lastAttemptAt:'2026-10-06T10:00:00Z'}};
test('editing holdings preserves a newer quote read inside the transaction',async()=>{const {api,docs}=harness({'users/u/assets/a':asset});const saved=await api.saveAsset('u',{...asset,qty:20,updatedAt:'two',quote:{nativePrice:1}},'one');assert.equal(saved.quote.nativePrice,110);assert.equal(docs.get('users/u/assets/a').qty,20);});
test('stale forms cannot overwrite newer edits or resurrect a deleted asset',async()=>{const {api,docs}=harness({'users/u/assets/a':asset});await assert.rejects(api.saveAsset('u',{...asset,qty:20},'older'),/其他裝置更新/);assert.equal(docs.get('users/u/assets/a').qty,10);docs.delete('users/u/assets/a');await assert.rejects(api.saveAsset('u',asset,'one'),/其他裝置刪除/);assert.equal(docs.has('users/u/assets/a'),false);});
test('quote refresh never overwrites quantities, costs, symbols or newer quotes',async()=>{const changed={...asset,symbol:'NEW',qty:99,costPer:75};const {api,docs}=harness({'users/u/assets/a':changed});const update={id:'a',mode:'stock',symbol:'TEST',quote:{nativePrice:200,fx:31,lastAttemptAt:'2026-10-06T11:00:00Z'}};assert.equal((await api.saveQuotes('u',[update])).length,0);assert.equal(docs.get('users/u/assets/a').qty,99);update.symbol='NEW';update.quote.lastAttemptAt='2026-10-06T09:00:00Z';assert.equal((await api.saveQuotes('u',[update])).length,0);update.quote.lastAttemptAt='2026-10-06T11:00:00Z';assert.equal((await api.saveQuotes('u',[update])).length,1);assert.equal(docs.get('users/u/assets/a').costPer,75);assert.equal(docs.get('users/u/assets/a').qty,99);});
test('publishing selects only chosen assets and keeps strategy audience separate',async()=>{const {api,docs}=harness({'users/u/assets/a':{...asset,finnhubKey:'SECRET',quote:{...asset.quote,apiKey:'SECRET'}},'users/u/assets/b':{...asset,id:'b',name:'Private'}});await api.publish('u','Owner',['a'],['viewer-portfolio'],['viewer-strategy']);const p=docs.get('sharedPortfolios/u');assert.equal(p.assets.length,1);assert.ok(!JSON.stringify(p).includes('SECRET'));assert.equal(p.viewerUids[0],'viewer-portfolio');assert.equal(docs.get('strategyAccess/u').viewerUids[0],'viewer-strategy');});
test('deleting a holding removes it from the published projection atomically',async()=>{const {api,docs}=harness({'users/u/assets/a':asset,'sharedPortfolios/u':{assets:[sharedAsset(asset)],viewerUids:['v']}});await api.deleteAsset('u','a');assert.equal(docs.has('users/u/assets/a'),false);assert.equal(docs.get('sharedPortfolios/u').assets.length,0);});
test('legacy migration backs up source, uses stable generated IDs and does not run twice',async()=>{const legacy={assets:[{name:'Cash',mode:'manual',value:100},{...asset,id:'legacy',value:35200}],history:[{date:'2026-10-06',total:35300}],settings:{goal:12345},quotes:{fx:32}};const {api,docs}=harness({'users/u':legacy});const loaded=await api.loadUser({uid:'u',displayName:'Owner'});assert.equal(loaded.assets.length,2);const cash=[...docs.entries()].find(([key,a])=>key.startsWith('users/u/assets/')&&a.name==='Cash');assert.equal(cash[0].split('/').at(-1),cash[1].id);assert.equal(docs.get('users/u/backups/v1').assets.length,2);assert.equal(docs.get('users/u').schemaVersion,2);assert.equal(docs.get('users/u').assets,undefined);assert.equal(loaded.settings.goal,12345);docs.get('users/u/assets/legacy').qty=42;await api.loadUser({uid:'u',displayName:'Owner'});assert.equal(docs.get('users/u/assets/legacy').qty,42);});
test('automatic daily snapshot preserves an existing same-day record',async()=>{const {api,docs}=harness({'users/u/history/2026-10-06':{date:'2026-10-06',total:100}});await api.snapshot('u','2026-10-06',200,false);assert.equal(docs.get('users/u/history/2026-10-06').total,100);await api.snapshot('u','2026-10-06',200,true);assert.equal(docs.get('users/u/history/2026-10-06').total,200);});
