import {createRequire} from "node:module";
import assert from "node:assert/strict";
import {mkdir} from "node:fs/promises";
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+"/qa.cjs" : import.meta.url);
const {chromium}=require("playwright");
const base=process.env.WEALTH_TEST_URL||"http://127.0.0.1:8000";
const output=new URL("../previews/",import.meta.url).pathname;
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const errors=[];page.on("pageerror",e=>errors.push(e.message));
await page.route(/fonts\.(googleapis|gstatic)\.com/,route=>route.abort());
await page.goto(base+"/?demo=1",{waitUntil:"networkidle"});
await page.locator("#appView:not(.hidden)").waitFor();
assert.equal(await page.locator("#navigation button").count(),5);
await page.screenshot({path:output+"desktop-overview.png",fullPage:true});
for(const width of [320,360,390,640,850,1440]) {
  await page.setViewportSize({width,height:1000});
  const metrics=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));
  assert.ok(metrics.scroll<=metrics.viewport+1,`overview overflow at ${width}: ${JSON.stringify(metrics)}`);
}
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:output+"mobile-overview.png",fullPage:true});
await page.locator('#navigation [data-page="assets"]').click();
await page.locator('#content [data-action="add-asset"]').click();
await page.locator('#assetForm [name="mode"]').selectOption("manual");
await page.locator('#assetForm [name="name"]').fill("測試現金");
await page.locator('#assetForm [type="submit"]').click();
await page.locator('#assetError').filter({hasText:"請填目前價值"}).waitFor();
await page.locator('#assetForm [name="value"]').fill("10000");
await page.locator('#assetForm [name="cost"]').fill("9000");
await page.locator('#assetForm [type="submit"]').click();
await page.locator('#assetDialog').waitFor({state:"hidden"});
await page.locator('#assetSearch').fill("測試現金");
assert.equal(await page.locator('#assetRows tbody tr').count(),1);
assert.match(await page.locator('#assetRows').innerText(),/1,000/);
await page.locator('#assetSearch').fill("");
await page.screenshot({path:output+"mobile-holdings.png",fullPage:true});
await page.locator('#navigation [data-page="sharing"]').click();
await page.locator('[data-share-asset]').first().uncheck();
await page.locator('[data-strategy-viewer]').first().uncheck();
await page.locator('[data-action="publish"]').click();
await page.locator('#content').getByText("分享設定已儲存").count();
await page.locator('#inviteForm [name="email"]').fill("friend@example.com");
await page.locator('#inviteForm [type="submit"]').click();
await page.locator('.invite-item').filter({hasText:"friend@example.com"}).waitFor();
await page.screenshot({path:output+"mobile-sharing.png",fullPage:true});
await page.locator('#friendSelect').selectOption("demo-friend");
assert.equal(await page.locator('#content [data-action="edit-asset"]').count(),0);
assert.match(await page.locator('#content').innerText(),/唯讀/);
await page.locator('#friendSelect').selectOption("self");
await page.locator('[data-tab="short"]').click();
await page.locator('#content [data-action="add-strategy"]').first().click();
await page.locator('#strategyForm [name="title"]').fill("測試策略");
await page.locator('#strategyForm [name="symbol"]').fill("TEST");
await page.locator('#strategyForm [name="thesis"]').fill("已測試文字與條件的保存。");
await page.locator('#strategyForm [name="entry"]').fill("出現條件才進場");
await page.locator('#strategyForm [name="invalidation"]').fill("跌破條件就退出");
await page.locator('#strategyForm [type="submit"]').click();
await page.locator('#strategyDialog').waitFor({state:"hidden"});
await page.locator('.strategy-card').filter({hasText:"測試策略"}).waitFor();
assert.match(await page.locator('.strategy-card').filter({hasText:"測試策略"}).innerText(),/私人草稿/);
await page.locator('#navigation [data-page="settings"]').click();
await page.locator('#goalForm [name="goal"]').fill("4000000");
await page.locator('#goalForm [type="submit"]').click();
assert.equal(await page.locator('#goalForm [name="goal"]').inputValue(),"4000000");
await page.locator('#navigation [data-page="history"]').click();
await page.locator('#content [data-action="snapshot"]').click();
assert.match(await page.locator('.history-table tbody').innerText(),/NT\$/);
for(const name of ["home","assets","sharing","history","settings"]) {
  await page.locator(`#navigation [data-page="${name}"]`).click();
  const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));
  assert.ok(size.scroll<=size.viewport+1,`${name} mobile overflow`);
}
assert.deepEqual(errors,[]);
console.log("UI PASS: 6 widths, all 5 pages, asset validation/add/search, separate audiences, invite, friend read-only, strategy draft, settings, daily snapshot; no page errors.");
await browser.close();
